INSERT INTO "breeds" (name, section, origin) 
VALUES
('ENGLISH POINTER', 'British and Irish Pointers and Setters', 'GREAT BRITAIN'),
('ENGLISH SETTER', 'British and Irish Pointers and Setters', 'GREAT BRITAIN'),
('KERRY BLUE TERRIER', 'Large and medium sized Terriers', 'IRELAND'),
('CAIRN TERRIER', 'Small sized Terriers', 'GREAT BRITAIN'),
('ENGLISH COCKER SPANIEL', 'Flushing Dogs', 'GREAT BRITAIN'),
('GORDON SETTER', 'British and Irish Pointers and Setters', 'GREAT BRITAIN'),
('AIREDALE TERRIER', 'Large and medium sized Terriers', 'GREAT BRITAIN'),
('AUSTRALIAN TERRIER', 'Small sized Terriers', 'AUSTRALIA'),
('BEDLINGTON TERRIER', 'Large and medium sized Terriers', 'GREAT BRITAIN'),
('BORDER TERRIER', 'Large and medium sized Terriers', 'GREAT BRITAIN'),
('BULL TERRIER', 'Bull type Terriers', 'GREAT BRITAIN'),
('FOX TERRIER (SMOOTH)', 'Large and medium sized Terriers', 'GREAT BRITAIN'),
('ENGLISH TOY TERRIER (BLACK &TAN)', 'Toy Terriers', 'GREAT BRITAIN'),
('SWEDISH VALLHUND', 'Nordic Watchdogs and Herders', 'SWEDEN'),
('BELGIAN SHEPHERD DOG', 'Sheepdogs', 'BELGIUM'),
('OLD ENGLISH SHEEPDOG', 'Sheepdogs', 'GREAT BRITAIN'),
('GRIFFON NIVERNAIS', 'Scent hounds', 'FRANCE'),
('BRIQUET GRIFFON VENDEEN', 'Scent hounds', 'FRANCE'),
('ARIEGEOIS', 'Scent hounds', 'FRANCE'),
('GASCON SAINTONGEOIS', 'Scent hounds', 'FRANCE'),
('GREAT GASCONY BLUE', 'Scent hounds', 'FRANCE'),
('POITEVIN', 'Scent hounds', 'FRANCE'),
('BILLY', 'Scent hounds', 'FRANCE'),
('ARTOIS HOUND', 'Scent hounds', 'FRANCE'),
('PORCELAINE', 'Scent hounds', 'FRANCE'),
('SMALL BLUE GASCONY', 'Scent hounds', 'FRANCE'),
('BLUE GASCONY GRIFFON', 'Scent hounds', 'FRANCE'),
('GRAND BASSET GRIFFON VENDEEN', 'Scent hounds', 'FRANCE'),
('NORMAN ARTESIEN BASSET', 'Scent hounds', 'FRANCE'),
('BLUE GASCONY BASSET', 'Scent hounds', 'FRANCE'),
('BASSET FAUVE DE BRETAGNE', 'Scent hounds', 'FRANCE'),
('PORTUGUESE WATER DOG', 'Water Dogs', 'PORTUGAL'),
('WELSH CORGI (CARDIGAN)', 'Sheepdogs', 'GREAT BRITAIN'),
('WELSH CORGI (PEMBROKE)', 'Sheepdogs', 'GREAT BRITAIN'),
('IRISH SOFT COATED WHEATEN TERRIER', 'Large and medium sized Terriers', 'IRELAND'),
('YUGOSLAVIAN SHEPHERD DOG - SHARPLANINA', 'Molossian type', 'NORTH MACEDONIA, SERBIA'),
('JÄMTHUND', 'Nordic Hunting Dogs', 'SWEDEN'),
('BASENJI', 'Primitive type', 'CENTRAL AFRICA'),
('BERGER DE BEAUCE', 'Sheepdogs', 'FRANCE'),
('BERNESE MOUNTAIN DOG', 'Swiss Mountain- and Cattledogs', 'SWITZERLAND'),
('APPENZELL CATTLE DOG', 'Swiss Mountain- and Cattledogs', 'SWITZERLAND'),
('ENTLEBUCH CATTLE DOG', 'Swiss Mountain- and Cattledogs', 'SWITZERLAND'),
('KARELIAN BEAR DOG', 'Nordic Hunting Dogs', 'FINLAND'),
('FINNISH SPITZ', 'Nordic Hunting Dogs', 'FINLAND'),
('NEWFOUNDLAND', 'Molossian type', 'CANADA'),
('FINNISH HOUND', 'Scent hounds', 'FINLAND'),
('POLISH HOUND', 'Scent hounds', 'POLAND'),
('KOMONDOR', 'Sheepdogs', 'HUNGARY'),
('KUVASZ', 'Sheepdogs', 'HUNGARY'),
('PULI', 'Sheepdogs', 'HUNGARY'),
('PUMI', 'Sheepdogs', 'HUNGARY'),
('HUNGARIAN SHORT-HAIRED POINTER (VIZSLA)', 'Continental Pointing Dogs', 'HUNGARY'),
('GREAT SWISS MOUNTAIN DOG', 'Swiss Mountain- and Cattledogs', 'SWITZERLAND'),
('SWISS HOUND', 'Scent hounds', 'SWITZERLAND'),
('SMALL SWISS HOUND', 'Scent hounds', 'SWITZERLAND'),
('ST. BERNARD', 'Molossian type', 'SWITZERLAND'),
('COARSE-HAIRED STYRIAN HOUND', 'Scent hounds', 'AUSTRIA'),
('AUSTRIAN BLACK AND TAN HOUND', 'Scent hounds', 'AUSTRIA'),
('AUSTRIAN  PINSCHER', 'Pinscher and Schnauzer type', 'AUSTRIA'),
('MALTESE', 'Bichons and related breeds', 'CENTRAL MEDITERRANEAN BASIN'),
('FAWN BRITTANY GRIFFON', 'Scent hounds', 'FRANCE'),
('PETIT BASSET GRIFFON VENDEEN', 'Scent hounds', 'FRANCE'),
('TYROLEAN HOUND', 'Scent hounds', 'AUSTRIA'),
('LAKELAND TERRIER', 'Large and medium sized Terriers', 'GREAT BRITAIN'),
('MANCHESTER TERRIER', 'Large and medium sized Terriers', 'GREAT BRITAIN'),
('NORWICH TERRIER', 'Small sized Terriers', 'GREAT BRITAIN'),
('SCOTTISH TERRIER', 'Small sized Terriers', 'GREAT BRITAIN'),
('SEALYHAM TERRIER', 'Small sized Terriers', 'GREAT BRITAIN'),
('SKYE TERRIER', 'Small sized Terriers', 'GREAT BRITAIN'),
('STAFFORDSHIRE BULL TERRIER', 'Bull type Terriers', 'GREAT BRITAIN'),
('CONTINENTAL TOY SPANIEL', 'Continental Toy Spaniel and others', 'BELGIUM, FRANCE'),
('WELSH TERRIER', 'Large and medium sized Terriers', 'GREAT BRITAIN'),
('GRIFFON BRUXELLOIS', 'Small Belgian Dogs', 'BELGIUM'),
('GRIFFON BELGE', 'Small Belgian Dogs', 'BELGIUM'),
('PETIT BRABANÇON', 'Small Belgian Dogs', 'BELGIUM'),
('SCHIPPERKE', 'Sheepdogs', 'BELGIUM'),
('BLOODHOUND', 'Scent hounds', 'BELGIUM'),
('WEST HIGHLAND WHITE TERRIER', 'Small sized Terriers', 'GREAT BRITAIN'),
('YORKSHIRE TERRIER', 'Toy Terriers', 'GREAT BRITAIN'),
('CATALAN SHEEPDOG', 'Sheepdogs', 'SPAIN'),
('SHETLAND SHEEPDOG', 'Sheepdogs', 'GREAT BRITAIN'),
('IBIZAN PODENCO', 'Primitive type - Hunting Dogs', 'SPAIN'),
('BURGOS POINTING DOG', 'Continental Pointing Dogs', 'SPAIN'),
('SPANISH MASTIFF', 'Molossian type', 'SPAIN'),
('PYRENEAN MASTIFF', 'Molossian type', 'SPAIN'),
('PORTUGUESE SHEEPDOG', 'Sheepdogs', 'PORTUGAL'),
('PORTUGUESE WARREN HOUND-PORTUGUESE PODENGO', 'Primitive type - Hunting Dogs', 'PORTUGAL'),
('BRITTANY SPANIEL', 'Continental Pointing Dogs', 'FRANCE'),
('RAFEIRO OF ALENTEJO', 'Molossian type', 'PORTUGAL'),
('GERMAN SPITZ', 'European Spitz', 'GERMANY'),
('GERMAN WIRE- HAIRED POINTING DOG', 'Continental Pointing Dogs', 'GERMANY'),
('WEIMARANER', 'Continental Pointing Dogs', 'GERMANY'),
('WESTPHALIAN DACHSBRACKE', 'Scent hounds', 'GERMANY'),
('FRENCH BULLDOG', 'Small Molossian type Dogs', 'FRANCE'),
('KLEINER MÜNSTERLÄNDER', 'Continental Pointing Dogs', 'GERMANY'),
('GERMAN HUNTING TERRIER', 'Large and medium sized Terriers', 'GERMANY'),
('GERMAN SPANIEL', 'Flushing Dogs', 'GERMANY'),
('FRENCH WATER DOG', 'Water Dogs', 'FRANCE'),
('BLUE PICARDY SPANIEL', 'Continental Pointing Dogs', 'FRANCE'),
('WIRE-HAIRED POINTING GRIFFON KORTHALS', 'Continental Pointing Dogs', 'FRANCE'),
('PICARDY SPANIEL', 'Continental Pointing Dogs', 'FRANCE'),
('CLUMBER SPANIEL', 'Flushing Dogs', 'GREAT BRITAIN'),
('CURLY COATED RETRIEVER', 'Retrievers', 'GREAT BRITAIN'),
('GOLDEN RETRIEVER', 'Retrievers', 'GREAT BRITAIN'),
('BRIARD', 'Sheepdogs', 'FRANCE'),
('PONT-AUDEMER SPANIEL', 'Continental Pointing Dogs', 'FRANCE'),
('SAINT GERMAIN POINTER', 'Continental Pointing Dogs', 'FRANCE'),
('DOGUE DE BORDEAUX', 'Molossian type', 'FRANCE'),
('DEUTSCH LANGHAAR', 'Continental Pointing Dogs', 'GERMANY'),
('LARGE MUNSTERLANDER', 'Continental Pointing Dogs', 'GERMANY'),
('GERMAN SHORT- HAIRED POINTING DOG', 'Continental Pointing Dogs', 'GERMANY'),
('IRISH RED SETTER', 'British and Irish Pointers and Setters', 'IRELAND'),
('FLAT COATED RETRIEVER', 'Retrievers', 'GREAT BRITAIN'),
('LABRADOR RETRIEVER', 'Retrievers', 'GREAT BRITAIN'),
('FIELD SPANIEL', 'Flushing Dogs', 'GREAT BRITAIN'),
('IRISH WATER SPANIEL', 'Water Dogs', 'IRELAND'),
('ENGLISH SPRINGER SPANIEL', 'Flushing Dogs', 'GREAT BRITAIN'),
('WELSH SPRINGER SPANIEL', 'Flushing Dogs', 'GREAT BRITAIN'),
('SUSSEX SPANIEL', 'Flushing Dogs', 'GREAT BRITAIN'),
('KING CHARLES SPANIEL', 'English Toy Spaniels', 'GREAT BRITAIN'),
('SMÅLANDSSTÖVARE', 'Scent hounds', 'SWEDEN'),
('DREVER', 'Scent hounds', 'SWEDEN'),
('SCHILLERSTÖVARE', 'Scent hounds', 'SWEDEN'),
('HAMILTONSTÖVARE', 'Scent hounds', 'SWEDEN'),
('FRENCH POINTING DOG - GASCOGNE TYPE', 'Continental Pointing Dogs', 'FRANCE'),
('FRENCH POINTING DOG - PYRENEAN TYPE', 'Continental Pointing Dogs', 'FRANCE'),
('SWEDISH LAPPHUND', 'Nordic Watchdogs and Herders', 'SWEDEN'),
('CAVALIER KING CHARLES SPANIEL', 'English Toy Spaniels', 'GREAT BRITAIN'),
('PYRENEAN MOUNTAIN DOG', 'Molossian type', 'FRANCE'),
('PYRENEAN SHEEPDOG - SMOOTH FACED', 'Sheepdogs', 'FRANCE'),
('IRISH TERRIER', 'Large and medium sized Terriers', 'IRELAND'),
('BOSTON TERRIER', 'Small Molossian type Dogs', 'UNITED STATES OF AMERICA'),
('LONG-HAIRED PYRENEAN SHEEPDOG', 'Sheepdogs', 'FRANCE'),
('SLOVAKIAN CHUVACH', 'Sheepdogs', 'SLOVAKIA'),
('DOBERMANN', 'Pinscher and Schnauzer type', 'GERMANY'),
('BOXER', 'Molossian type', 'GERMANY'),
('LEONBERGER', 'Molossian type', 'GERMANY'),
('RHODESIAN RIDGEBACK', 'Related breeds', 'SOUTH AFRICA'),
('ROTTWEILER', 'Molossian type', 'GERMANY'),
('DACHSHUND', '', 'GERMANY'),
('BULLDOG', 'Molossian type', 'GREAT BRITAIN'),
('SERBIAN HOUND', 'Scent hounds', 'SERBIA'),
('ISTRIAN SHORT-HAIRED HOUND', 'Scent hounds', 'CROATIA'),
('ISTRIAN WIRE-HAIRED HOUND', 'Scent hounds', 'CROATIA'),
('DALMATIAN', 'Related breeds', 'CROATIA'),
('POSAVATZ HOUND', 'Scent hounds', 'CROATIA'),
('BOSNIAN BROKEN-HAIRED HOUND - CALLED BARAK', 'Scent hounds', 'BOSNIA AND HERZEGOVINA'),
('COLLIE ROUGH', 'Sheepdogs', 'GREAT BRITAIN'),
('BULLMASTIFF', 'Molossian type', 'GREAT BRITAIN'),
('GREYHOUND', 'Short-haired Sighthounds', 'GREAT BRITAIN'),
('ENGLISH FOXHOUND', 'Scent hounds', 'GREAT BRITAIN'),
('IRISH WOLFHOUND', 'Rough-haired Sighthounds', 'IRELAND'),
('BEAGLE', 'Scent hounds', 'GREAT BRITAIN'),
('WHIPPET', 'Short-haired Sighthounds', 'GREAT BRITAIN'),
('BASSET HOUND', 'Scent hounds', 'GREAT BRITAIN'),
('DEERHOUND', 'Rough-haired Sighthounds', 'GREAT BRITAIN'),
('ITALIAN SPINONE', 'Continental Pointing Dogs', 'ITALY'),
('GERMAN SHEPHERD DOG', 'Sheepdogs', 'GERMANY'),
('AMERICAN COCKER SPANIEL', 'Flushing Dogs', 'UNITED STATES OF AMERICA'),
('DANDIE DINMONT TERRIER', 'Small sized Terriers', 'GREAT BRITAIN'),
('FOX TERRIER (WIRE)', 'Large and medium sized Terriers', 'GREAT BRITAIN'),
('CASTRO LABOREIRO DOG', 'Molossian type', 'PORTUGAL'),
('BOUVIER DES ARDENNES', 'Cattledogs (except Swiss Cattledogs)', 'BELGIUM'),
('POODLE', 'Poodle', 'FRANCE'),
('ESTRELA MOUNTAIN DOG', 'Molossian type', 'PORTUGAL'),
('FRENCH SPANIEL', 'Continental Pointing Dogs', 'FRANCE'),
('PICARDY SHEEPDOG', 'Sheepdogs', 'FRANCE'),
('ARIEGE POINTING DOG', 'Continental Pointing Dogs', 'FRANCE'),
('BOURBONNAIS POINTING DOG', 'Continental Pointing Dogs', 'FRANCE'),
('AUVERGNE POINTER', 'Continental Pointing Dogs', 'FRANCE'),
('GIANT SCHNAUZER', 'Pinscher and Schnauzer type', 'GERMANY'),
('SCHNAUZER', 'Pinscher and Schnauzer type', 'GERMANY'),
('MINIATURE SCHNAUZER', 'Pinscher and Schnauzer type', 'GERMANY'),
('GERMAN PINSCHER', 'Pinscher and Schnauzer type', 'GERMANY'),
('MINIATURE PINSCHER', 'Pinscher and Schnauzer type', 'GERMANY'),
('AFFENPINSCHER', 'Pinscher and Schnauzer type', 'GERMANY'),
('PORTUGUESE POINTING DOG', 'Continental Pointing Dogs', 'PORTUGAL'),
('SLOUGHI', 'Short-haired Sighthounds', 'MOROCCO'),
('FINNISH LAPPONIAN DOG', 'Nordic Watchdogs and Herders', 'FINLAND'),
('HOVAWART', 'Molossian type', 'GERMANY'),
('BOUVIER DES FLANDRES', 'Cattledogs (except Swiss Cattledogs)', 'BELGIUM, FRANCE'),
('KROMFOHRLÄNDER', 'Kromfohrländer', 'GERMANY'),
('BORZOI - RUSSIAN HUNTING SIGHTHOUND', 'Long-haired or fringed Sighthounds', 'RUSSIA'),
('BERGAMASCO SHEPHERD DOG', 'Sheepdogs', 'ITALY'),
('ITALIAN VOLPINO', 'European Spitz', 'ITALY'),
('BOLOGNESE', 'Bichons and related breeds', 'ITALY'),
('NEAPOLITAN MASTIFF', 'Molossian type', 'ITALY'),
('ITALIAN ROUGH-HAIRED SEGUGIO', 'Scent hounds', 'ITALY'),
("CIRNECO DELL''ETNA", 'Primitive type - Hunting Dogs', 'ITALY'),
('ITALIAN SIGHTHOUND', 'Short-haired Sighthounds', 'ITALY'),
('MAREMMA AND THE ABRUZZES SHEEPDOG', 'Sheepdogs', 'ITALY'),
('ITALIAN POINTING DOG', 'Continental Pointing Dogs', 'ITALY'),
('NORWEGIAN HOUND', 'Scent hounds', 'NORWAY'),
('SPANISH HOUND', 'Scent hounds', 'SPAIN'),
('CHOW CHOW', 'Asian Spitz and related breeds', 'CHINA'),
('JAPANESE CHIN', 'Japan Chin and Pekingese', 'JAPAN'),
('PEKINGESE', 'Japan Chin and Pekingese', 'CHINA'),
('SHIH TZU', 'Tibetan breeds', 'Tibet (China)'),
('TIBETAN TERRIER', 'Tibetan breeds', 'Tibet (China)'),
('CANADIAN ESKIMO DOG', 'Nordic Sledge Dogs', 'CANADA'),
('SAMOYED', 'Nordic Sledge Dogs', 'NORTHERN RUSSIA, SIBERIA'),
('HANOVERIAN SCENT HOUND', 'Leash (scent) Hounds', 'GERMANY'),
('HELLENIC HOUND', 'Scent hounds', 'GREECE'),
('BICHON FRISE', 'Bichons and related breeds', 'BELGIUM, FRANCE'),
('PUDELPOINTER', 'Continental Pointing Dogs', 'GERMANY'),
('BAVARIAN MOUNTAIN SCENT HOUND', 'Leash (scent) Hounds', 'GERMANY'),
('CHIHUAHUA', 'Chihuahueno', 'MEXICO'),
('FRENCH TRICOLOUR HOUND', 'Scent hounds', 'FRANCE'),
('FRENCH WHITE & BLACK HOUND', 'Scent hounds', 'FRANCE'),
('FRISIAN WATER DOG', 'Water Dogs', 'THE NETHERLANDS'),
('STABIJHOUN', 'Continental Pointing Dogs', 'THE NETHERLANDS'),
('DUTCH SHEPHERD DOG', 'Sheepdogs', 'THE NETHERLANDS'),
('DRENTSCHE PARTRIDGE DOG', 'Continental Pointing Dogs', 'THE NETHERLANDS'),
('FILA BRASILEIRO', 'Molossian type', 'BRAZIL'),
('LANDSEER (EUROPEAN CONTINENTAL TYPE)', 'Molossian type', 'GERMANY, SWITZERLAND'),
('LHASA APSO', 'Tibetan breeds', 'Tibet (China)'),
('AFGHAN HOUND', 'Long-haired or fringed Sighthounds', 'AFGHANISTAN'),
('SERBIAN TRICOLOUR HOUND', 'Scent hounds', 'SERBIA'),
('TIBETAN MASTIFF', 'Molossian type', 'Tibet (China)'),
('TIBETAN SPANIEL', 'Tibetan breeds', 'Tibet (China)'),
('DEUTSCH STICHELHAAR', 'Continental Pointing Dogs', 'GERMANY'),
('LITTLE LION DOG', 'Bichons and related breeds', 'FRANCE'),
('XOLOITZCUINTLE', 'Primitive type', 'MEXICO'),
('GREAT DANE', 'Molossian type', 'GERMANY'),
('AUSTRALIAN SILKY TERRIER', 'Toy Terriers', 'AUSTRALIA'),
('NORWEGIAN BUHUND', 'Nordic Watchdogs and Herders', 'NORWAY'),
('MUDI', 'Sheepdogs', 'HUNGARY'),
('HUNGARIAN WIRE-HAIRED POINTER', 'Continental Pointing Dogs', 'HUNGARY'),
('HUNGARIAN GREYHOUND', 'Short-haired Sighthounds', 'HUNGARY'),
('HUNGARIAN HOUND - TRANSYLVANIAN SCENT HOUND', 'Scent hounds', 'HUNGARY'),
('NORWEGIAN ELKHOUND GREY', 'Nordic Hunting Dogs', 'NORWAY'),
('ALASKAN MALAMUTE', 'Nordic Sledge Dogs', 'UNITED STATES OF AMERICA'),
('SLOVAKIAN HOUND', 'Scent hounds', 'SLOVAKIA'),
('BOHEMIAN WIRE-HAIRED POINTING GRIFFON', 'Continental Pointing Dogs', 'CZECH REPUBLIC'),
('CESKY TERRIER', 'Small sized Terriers', 'CZECH REPUBLIC'),
('ATLAS MOUNTAIN DOG (AIDI)', 'Molossian type', 'MOROCCO'),
('PHARAOH HOUND', 'Primitive type', 'MALTA'),
('MAJORCA MASTIFF', 'Molossian type', 'SPAIN'),
('HAVANESE', 'Bichons and related breeds', 'CUBA'),
('POLISH LOWLAND SHEEPDOG', 'Sheepdogs', 'POLAND'),
('TATRA SHEPHERD DOG', 'Sheepdogs', 'POLAND'),
('PUG', 'Small Molossian type Dogs', 'CHINA'),
('ALPINE DACHSBRACKE', 'Leash (scent) Hounds', 'AUSTRIA'),
('AKITA', 'Asian Spitz and related breeds', 'JAPAN'),
('SHIBA', 'Asian Spitz and related breeds', 'JAPAN'),
('JAPANESE TERRIER', 'Small sized Terriers', 'JAPAN'),
('TOSA', 'Molossian type', 'JAPAN'),
('HOKKAIDO', 'Asian Spitz and related breeds', 'JAPAN'),
('JAPANESE SPITZ', 'Asian Spitz and related breeds', 'JAPAN'),
('CHESAPEAKE BAY RETRIEVER', 'Retrievers', 'UNITED STATES OF AMERICA'),
('MASTIFF', 'Molossian type', 'GREAT BRITAIN'),
('NORWEGIAN LUNDEHUND', 'Nordic Hunting Dogs', 'NORWAY'),
('HYGEN HOUND', 'Scent hounds', 'NORWAY'),
('HALDEN HOUND', 'Scent hounds', 'NORWAY'),
('NORWEGIAN ELKHOUND BLACK', 'Nordic Hunting Dogs', 'NORWAY'),
('SALUKI', 'Long-haired or fringed Sighthounds', 'MIDDLE EAST'),
('SIBERIAN HUSKY', 'Nordic Sledge Dogs', 'UNITED STATES OF AMERICA'),
('BEARDED COLLIE', 'Sheepdogs', 'GREAT BRITAIN'),
('NORFOLK TERRIER', 'Small sized Terriers', 'GREAT BRITAIN'),
('CANAAN DOG', 'Primitive type', 'ISRAEL'),
('GREENLAND DOG', 'Nordic Sledge Dogs', 'GREENLAND'),
('NORRBOTTENSPITZ', 'Nordic Hunting Dogs', 'SWEDEN'),
('CROATIAN SHEPHERD DOG', 'Sheepdogs', 'CROATIA'),
('KARST SHEPHERD DOG', 'Molossian type', 'SLOVENIA'),
('MONTENEGRIN MOUNTAIN HOUND', 'Scent hounds', 'MONTENEGRO'),
('OLD DANISH POINTING DOG', 'Continental Pointing Dogs', 'DENMARK'),
('GRAND GRIFFON VENDEEN', 'Scent hounds', 'FRANCE'),
('COTON DE TULEAR', 'Bichons and related breeds', 'MADAGASCAR'),
('LAPPONIAN HERDER', 'Nordic Watchdogs and Herders', 'FINLAND'),
('SPANISH GREYHOUND', 'Short-haired Sighthounds', 'SPAIN'),
('AMERICAN STAFFORDSHIRE TERRIER', 'Bull type Terriers', 'UNITED STATES OF AMERICA'),
('AUSTRALIAN CATTLE DOG', 'Cattledogs (except Swiss Cattledogs)', 'AUSTRALIA'),
('CHINESE CRESTED DOG', 'Hairless Dogs', 'CHINA'),
('ICELANDIC SHEEPDOG', 'Nordic Watchdogs and Herders', 'ICELAND'),
('BEAGLE HARRIER', 'Scent hounds', 'FRANCE'),
('EURASIAN', 'Asian Spitz and related breeds', 'GERMANY'),
('DOGO ARGENTINO', 'Molossian type', 'ARGENTINA'),
('AUSTRALIAN KELPIE', 'Sheepdogs', 'AUSTRALIA'),
('OTTERHOUND', 'Scent hounds', 'GREAT BRITAIN'),
('HARRIER', 'Scent hounds', 'GREAT BRITAIN'),
('COLLIE SMOOTH', 'Sheepdogs', 'GREAT BRITAIN'),
('BORDER COLLIE', 'Sheepdogs', 'GREAT BRITAIN'),
('ROMAGNA WATER DOG', 'Water Dogs', 'ITALY'),
('GERMAN HOUND', 'Scent hounds', 'GERMANY'),
('BLACK AND TAN COONHOUND', 'Scent hounds', 'UNITED STATES OF AMERICA'),
('AMERICAN WATER SPANIEL', 'Water Dogs', 'UNITED STATES OF AMERICA'),
('IRISH GLEN OF IMAAL TERRIER', 'Large and medium sized Terriers', 'IRELAND'),
('AMERICAN FOXHOUND', 'Scent hounds', 'UNITED STATES OF AMERICA'),
('RUSSIAN-EUROPEAN LAIKA', 'Nordic Hunting Dogs', 'RUSSIA'),
('EAST SIBERIAN LAIKA', 'Nordic Hunting Dogs', 'RUSSIA'),
('WEST SIBERIAN LAIKA', 'Nordic Hunting Dogs', 'RUSSIA'),
('AZAWAKH', 'Short-haired Sighthounds', 'MALI'),
('DUTCH SMOUSHOND', 'Pinscher and Schnauzer type', 'THE NETHERLANDS'),
('SHAR PEI', 'Molossian type', 'CHINA'),
('PERUVIAN HAIRLESS DOG', 'Primitive type', 'PERU'),
('SAARLOOS WOLFHOND', 'Sheepdogs', 'THE NETHERLANDS'),
('NOVA SCOTIA DUCK TOLLING RETRIEVER', 'Retrievers', 'CANADA'),
('DUTCH SCHAPENDOES', 'Sheepdogs', 'THE NETHERLANDS'),
('NEDERLANDSE KOOIKERHONDJE', 'Flushing Dogs', 'THE NETHERLANDS'),
('BROHOLMER', 'Molossian type', 'DENMARK'),
('FRENCH WHITE AND ORANGE HOUND', 'Scent hounds', 'FRANCE'),
('KAI', 'Asian Spitz and related breeds', 'JAPAN'),
('KISHU', 'Asian Spitz and related breeds', 'JAPAN'),
('SHIKOKU', 'Asian Spitz and related breeds', 'JAPAN'),
('WIREHAIRED SLOVAKIAN POINTER', 'Continental Pointing Dogs', 'SLOVAKIA'),
('MAJORCA SHEPHERD DOG', 'Sheepdogs', 'SPAIN'),
('GREAT ANGLO-FRENCH TRICOLOUR HOUND', 'Scent hounds', 'FRANCE'),
('GREAT ANGLO-FRENCH WHITE AND BLACK HOUND', 'Scent hounds', 'FRANCE'),
('GREAT ANGLO-FRENCH WHITE & ORANGE HOUND', 'Scent hounds', 'FRANCE'),
('MEDIUM-SIZED ANGLO-FRENCH HOUND', 'Scent hounds', 'FRANCE'),
('SOUTH RUSSIAN SHEPHERD DOG', 'Sheepdogs', 'RUSSIA'),
('RUSSIAN BLACK TERRIER', 'Pinscher and Schnauzer type', 'RUSSIA'),
('CAUCASIAN SHEPHERD DOG', 'Molossian type', 'RUSSIA'),
('CANARIAN WARREN HOUND', 'Primitive type - Hunting Dogs', 'SPAIN'),
('IRISH RED AND WHITE SETTER', 'British and Irish Pointers and Setters', 'IRELAND'),
('KANGAL SHEPHERD DOG', 'Molossian type', 'TURKEY'),
('CZECHOSLOVAKIAN WOLFDOG', 'Sheepdogs', 'SLOVAKIA'),
('POLISH GREYHOUND', 'Short-haired Sighthounds', 'POLAND'),
('KOREA JINDO DOG', 'Asian Spitz and related breeds', 'REPUBLIC OF KOREA'),
('CENTRAL ASIA SHEPHERD DOG', 'Molossian type', 'RUSSIA'),
('SPANISH WATER DOG', 'Water Dogs', 'SPAIN'),
('ITALIAN SHORT-HAIRED SEGUGIO', 'Scent hounds', 'ITALY'),
('THAI RIDGEBACK DOG', 'Primitive type - Hunting Dogs', 'THAILAND'),
('PARSON RUSSELL TERRIER', 'Large and medium sized Terriers', 'GREAT BRITAIN'),
('SAINT MIGUEL CATTLE DOG', 'Molossian type', 'PORTUGAL'),
('BRAZILIAN TERRIER', 'Large and medium sized Terriers', 'BRAZIL'),
('AUSTRALIAN SHEPHERD', 'Sheepdogs', 'UNITED STATES OF AMERICA'),
('ITALIAN CANE CORSO', 'Molossian type', 'ITALY'),
('AMERICAN AKITA', 'Asian Spitz and related breeds', 'JAPAN'),
('JACK RUSSELL TERRIER', 'Small sized Terriers', 'GREAT BRITAIN'),
('PRESA CANARIO', 'Molossian type', 'SPAIN'),
('WHITE SWISS SHEPHERD DOG', 'Sheepdogs', 'SWITZERLAND'),
('TAIWAN DOG', 'Primitive type - Hunting Dogs', 'TAIWAN'),
('ROMANIAN MIORITIC SHEPHERD DOG', 'Sheepdogs', 'ROMANIA'),
('ROMANIAN CARPATHIAN SHEPHERD DOG', 'Sheepdogs', 'ROMANIA'),
('AUSTRALIAN STUMPY TAIL CATTLE DOG', 'Cattledogs (except Swiss Cattledogs)', 'AUSTRALIA'),
('RUSSIAN TOY', 'Continental Toy Spaniel and others', 'RUSSIA'),
('CIMARRÓN URUGUAYO', 'Molossian type', 'URUGUAY'),
('POLISH HUNTING DOG', 'Scent hounds', 'POLAND'),
('BOSNIAN AND HERZEGOVINIAN - CROATIAN SHEPHERD DOG', 'Molossian type', 'BOSNIA AND HERZEGOVINA, CROATIA'),
('DANISH-SWEDISH FARMDOG', 'Pinscher and Schnauzer type', 'DENMARK, SWEDEN'),
('ROMANIAN BUCOVINA SHEPHERD', 'Molossian type', 'ROMANIA'),
('THAI BANGKAEW DOG', 'Asian Spitz and related breeds', 'THAILAND'),
('MINIATURE BULL TERRIER', 'Bull type Terriers', 'GREAT BRITAIN'),
('LANCASHIRE HEELER', 'Sheepdogs', 'ENGLAND'),
('SEGUGIO MAREMMANO', 'Scent hounds', 'ITALY'),
('KINTAMANI-BALI DOG', 'Asian Spitz and related breeds', 'INDONESIA'),
('PRAGUE RATTER', 'Continental Toy Spaniel and others', 'CZECH REPUBLIC'),
('BOHEMIAN SHEPHERD DOG', 'Sheepdogs', 'CZECH REPUBLIC'),
('YAKUTIAN LAIKA', 'Nordic Sledge Dogs', 'RUSSIA'),
('ESTONIAN HOUND', 'Scent hounds', 'ESTONIA'),
('MINIATURE AMERICAN SHEPHERD', 'Sheepdogs', 'UNITED STATES OF AMERICA');