INSERT INTO "colors" (name) VALUES
('Red'),
('Brown'),
('Sedge'),
('Deadgrass'),
('Chocolate '),
('Lilac '),
('Liver '),
('Liver Brown '),
('Isabella'),
('Chocolate '),
('Cafe-au-lait'),
('Mouse-gray'),
('Parti'),
('White '),
('Flash'),
('Piebald'),
('Flowered'),
('Landseet'),
('Spotted')